"""Migration message

Revision ID: 1774505f0076
Revises: 
Create Date: 2024-12-21 17:15:51.178087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1774505f0076'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_logged_users_email', table_name='logged_users')
    op.drop_index('ix_logged_users_id', table_name='logged_users')
    op.drop_index('ix_logged_users_username', table_name='logged_users')
    op.drop_table('logged_users')
    op.drop_index('ix_employees_email', table_name='employees')
    op.drop_index('ix_employees_id', table_name='employees')
    op.drop_table('employees')
    op.drop_index('ix_posts_id', table_name='posts')
    op.drop_table('posts')
    op.drop_index('ix_doctors_id', table_name='doctors')
    op.drop_table('doctors')
    op.drop_index('ix_patients_PID', table_name='patients')
    op.drop_index('ix_patients_email', table_name='patients')
    op.drop_index('ix_patients_id', table_name='patients')
    op.drop_table('patients')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_index('userId', table_name='users')
    op.drop_index('username', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('userId', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('username', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('first_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('middle_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('last_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('is_verified', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('verified_at', mysql.DATETIME(), nullable=True),
    sa.Column('verified_by', mysql.DATETIME(), nullable=True),
    sa.Column('registered_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('username', 'users', ['username'], unique=True)
    op.create_index('userId', 'users', ['userId'], unique=True)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_table('patients',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('PID', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('fname', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('mname', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('lname', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('dob', mysql.DATETIME(), nullable=True),
    sa.Column('sex', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('preferred_language', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('occupation', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('address', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('phone_number', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('previous_medical_condition', mysql.VARCHAR(length=1024), nullable=False),
    sa.Column('emergency_contact', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('sergical_history', mysql.VARCHAR(length=1024), nullable=False),
    sa.Column('created_by', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_by', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_patients_id', 'patients', ['id'], unique=False)
    op.create_index('ix_patients_email', 'patients', ['email'], unique=True)
    op.create_index('ix_patients_PID', 'patients', ['PID'], unique=True)
    op.create_table('doctors',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fname', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_doctors_id', 'doctors', ['id'], unique=False)
    op.create_table('posts',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', mysql.VARCHAR(length=1024), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='posts_ibfk_1', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_posts_id', 'posts', ['id'], unique=False)
    op.create_table('employees',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fname', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('mname', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('lname', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('dob', mysql.DATETIME(), nullable=False),
    sa.Column('address', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('zipcode', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_employees_id', 'employees', ['id'], unique=False)
    op.create_index('ix_employees_email', 'employees', ['email'], unique=True)
    op.create_table('logged_users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('role', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hashed_password', mysql.VARCHAR(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_logged_users_username', 'logged_users', ['username'], unique=True)
    op.create_index('ix_logged_users_id', 'logged_users', ['id'], unique=False)
    op.create_index('ix_logged_users_email', 'logged_users', ['email'], unique=True)
    # ### end Alembic commands ###
